version: "3"
services:
  go-ddd-sample-account:
    container_name: go-ddd-sample-account
    image: go-ddd-sample-account
    build:
      context: .
      args:
        app: "account"
      dockerfile: ./docker/app/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - go-ddd-sample-db
  go-ddd-sample-address:
    container_name: go-ddd-sample-address
    image: go-ddd-sample-address
    build:
      context: .
      args:
        app: "address"
      dockerfile: ./docker/app/Dockerfile
    tty: true
    ports:
      - "8081:8081"
    depends_on:
      - go-ddd-sample-db
  go-ddd-sample-db:
    container_name: go-ddd-sample-db
    image: go-ddd-sample-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - go-ddd-sample-db:/var/lib/mysql
      - ./docker/db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
volumes:
  go-ddd-sample-db: