on:
  push:
    branches-ignore:
      - main

name: check_build

env:
  GO_VERSION: 1.18.10

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go runtime
        uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: make test

      - name: Build account
        run: make build app=account

      - name: Build address
        run: make build app=address

      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: |
            coverage.out

  check_build:
    name: check_build
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Finish
        run: echo "done"
